<script>
  import SectionWrapper from "./SectionWrapper.svelte";

  let faqs = [
    
  {
    question: "How does the color palette generator work?",
    ans: "The color palette generator works by generating a set of harmonious colors based on various algorithms such as complementary, triadic, analogous, etc. It takes input parameters such as base color, number of colors, and harmony type to create a visually appealing palette."
  },
  {
    question: "Can I customize the number of colors in the generated palette?",
    ans: "Yes, you can customize the number of colors in the generated palette. Most color palette generators allow users to specify the number of colors they want in the palette, ranging from as few as two to as many as desired."
  },
  {
    question: "What is a base color, and how is it used in the palette generation?",
    ans: "A base color is the starting point for generating the color palette. It serves as a reference point, and the other colors in the palette are harmoniously derived from it. Users can either manually input a base color or select it from a color picker tool."
  },
  {
    question: "Can I export the generated color palette?",
    ans: "Yes, most color palette generators offer options to export the generated palette. You can typically export the palette in various formats such as PNG, JPEG, SVG, or as a list of color codes (hexadecimal, RGB, etc.). This allows you to use the generated palette in your design projects."
  },
  {
    question: "Are there options to adjust the color harmony type?",
    ans: "Yes, color palette generators often provide options to adjust the harmony type. You can choose from different harmony types such as complementary, analogous, triadic, tetradic, monochromatic, and more. This flexibility allows you to create palettes with different aesthetic effects."
  },
  {
    question: "Can I save and revisit color palettes generated by the tool?",
    ans: "Many color palette generators offer the ability to save and revisit generated color palettes. This feature allows users to store their favorite palettes for future reference or share them with others. Saved palettes are usually accessible through a user account or saved as files on your device."
  },
  {
    question: "Is there a way to preview how the generated palette will look in a design?",
    ans: "Yes, some color palette generators offer a preview feature that allows you to see how the generated palette will look in a design context. This can be useful for assessing the overall visual impact of the palette and making any necessary adjustments before finalizing your design."
  },
];

  
</script>

<SectionWrapper id="FAQs">
  <div
    class="flex flex-col gap-10 sm:gap-24 py-20 flex-1 items-center justify-center"
  >
    <div class="flex flex-col gap-2">
      <p class="opacity-60 text-base sm:text-lg md:text-xl text-center">
        Still have questions?
      </p>
      <h3
        class="text-4xl sm:text-5xl md:text-6xl max-w-[1000px] mx-auto w-full font-semibold text-center"
      >
        Frequently Asked Questions
      </h3>
    </div>
    <div class="flex flex-col gap-8 sm:gap-10 md:gap-14 w-full">
        {#each faqs as faq}
            <div class="flex flex-col gap-2 text-left max-w-[800px] w-full mx-auto relative p-4 px-6">
                <div class="absolute top-0 left-0 w-1/3 h-[1px] bg-slate-950 -translate-x-4"></div>

                <div class="absolute top-0 left-0 h-2/3 w-[1px] bg-slate-950 -translate-y-4"></div>
                <h4 class="text-lg sm:text-xl md:text-2xl pt-2">{faq.question}</h4>
                <p class="pl-2">{faq.ans}</p>
            </div>
        {/each}
    </div>
  </div>
</SectionWrapper>
